### PR TITLE
✨ ported to 1.20.1 (mostly)

### PR DESCRIPTION
**Pull request by sugisaru**
i added TODOS to unfinished and prolly inaccurate fixes

### CODE REVIEW

**Comment by FoxMcloud5655** [comment]
I hate to say it, but this probably won't be accepted...  We're all pretty strong proponents for NeoForged.  Switch it over, and I'm sure it'll have a much better chance of being accepted.

**Comment by sugisaru** [comment]
> I hate to say it, but this probably won't be accepted... We're all pretty strong proponents for NeoForged. Switch it over, and I'm sure it'll have a much better chance of being accepted.

yea thank ya! @KitsuneAlex already told me what's happening
should've waited for covers answer instead of just doing it but that's my bad, too sad :/
i will look forward into switching to NeoForged, seems like a nice new ModLoader and I'm too happy to try it out! :3

**Comment by sugisaru** [comment]
changed Forge -> NeoForge in 3b230dc71e949d7d6b5a7efbf066c1c604ce5fb8 :heart:

**Comment by covers1624** [comment]
Thanks for your hard work!

However, the 1.20.1 port was already completed weeks ago, it was just not pushed ._.

I plan to finish up a few bits and pieces later this week and have something ready to use by the weekend.

Feel free to poke around the port and submit fixes for anything you notice.

**Pull request closed without merging**
