### PR TITLE
Fix reading string with spaces in LDC instruction

### PR DESCRIPTION
**Pull request by miuirussia**

### CODE REVIEW

**Comment by covers1624** [comment]
Realistically you shouldn't need to Inject and LDC nodes, but this is a fair fix. I do have one suggestion.

**Comment by covers1624** [comment]
Eh forget the suggestion.. :P

**Comment by miuirussia** [comment]
It's for patches like this:
```
list n_ModList
ALOAD 0
ALOAD 0
GETFIELD net/minecraftforge/fml/client/GuiModList.fontRendererObj : Lnet/minecraft/client/gui/FontRenderer;
LDC "Mod List"
ILOAD 4
BIPUSH 16
LDC 16777215

list i_ModList
ALOAD 0
ALOAD 0
GETFIELD net/minecraftforge/fml/client/GuiModList.fontRendererObj : Lnet/minecraft/client/gui/FontRenderer;
LDC "gui.mod_list"
ICONST_0
ANEWARRAY java/lang/Object
INVOKESTATIC net/minecraft/client/resources/I18n.func_135052_a (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
ILOAD 4
BIPUSH 16
LDC 16777215
```

**Comment by covers1624** [comment]
Fair enough, you can use LDC * instead if LDC "Mod List"

**Comment by miuirussia** [comment]
How to change net/minecraftforge/fml/client/GuiModList.initGui()V method, that extends GuiScreen from MC? ObfMapping will work with this? Should I use srg, original of obfuscated name? Because I try with SRG and it not patched :(

**Comment by covers1624** [comment]
SRG, it should be fine.

**Comment by miuirussia** [comment]
Not working

**Comment by miuirussia** [comment]
ccl_modular:
[net#minecraftforge#fml#client#GuiModList.txt](https://github.com/TheCBProject/CodeChickenLib/files/907724/net.minecraftforge.fml.client.GuiModList.txt)

Crash report:
[crash-2017-04-08_22.21.11-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/907725/crash-2017-04-08_22.21.11-client.txt)

Mod src:
https://github.com/miuirussia/BaseMod

**Comment by covers1624** [comment]
It will, has to be something you are doing. By "Not Working" it should throw something in the console.

**Comment by miuirussia** [comment]
Full console log:
[latest.txt](https://github.com/TheCBProject/CodeChickenLib/files/907727/latest.txt)

**Comment by covers1624** [comment]
You are supressing some error thrown by your transformer most likely.

**Comment by miuirussia** [comment]
try - catch while transform or while adding transformers?

**Comment by covers1624** [comment]
while transforming

**Comment by miuirussia** [comment]
Ok, will test. Thanks!

**Comment by miuirussia** [comment]
java.lang.RuntimeException: java.lang.RuntimeException: Method not found: [net/minecraftforge/fml/client/GuiModList.func_73866_w_()V]

**Comment by covers1624** [comment]
Ah, The reader has some minor issues when working on non minecraft classes + sorting index. As All mod classes never use OBF names they use SRG, the pipe is designed to use OBF. Ill be reworking this in 1.11, but for now, just copy ASMReader and remove the .toClassLoading calls on ObfMapping's

**Comment by covers1624** [comment]
doing that you will have to put this on your IFMLLoadingPlugin implementation, @IFMLLoadingPlugin.SortingIndex (1001)

**Comment by miuirussia** [comment]
Ok, I test it

UPD: It works!

**Pull request merged**
