### PR TITLE
Fixed setLightMap not working

### PR DESCRIPTION
**Pull request by nikita488**

### CODE REVIEW

**Comment by covers1624** [comment]
Can you roll back the change to FG please.

**Comment by nikita488** [comment]
I think i done this now?

**Comment by covers1624** [comment]
ok, so what is your reasoning behind removing the defaulted 3rd and 4th argument in the packing section? also that cast is doing nothing.. you are taking a whole number casting to a double then multiplying by a whole number witch gets you a whole number.

**Comment by nikita488** [comment]
About arguments, I don't see that they are doing something :/
About double cast, without double cast it just send 0, 0, with double cast it send (for example if brightness 220) 0.006348, 0

**Comment by covers1624** [comment]
ok, so there are 4 arguments for everything because the 4th is essentially scale, well actually what all values are multiplied by when calculating on screen cords. regarding the cast, the cast ill put it in because i somewhat see your point if (int / int) = int compared to (double / int) = double

**Pull request closed without merging**
